_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: telegraf-ds
helmRelease: telegraf
helmRepo: https://helm.influxdata.com/
helmValues: helm/values.yaml
helmVersion: '1.1.35'
homepageEnabled: false
ingress: false
labels: ''
name: telegraf
namespace: telegraf
pvc: false
reloader: true
resources:
- external-secrets.yaml
- rbac.yaml
service: false
serviceAccount: false
upstreamURL: https://www.influxdata.com/time-series-platform/telegraf/
url: https://github.com/charlesthomas/homelab-telegraf
