---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegraf

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-telegraf

resources:
- resources/external-secrets.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
patches:
helmCharts:
- name: telegraf-ds
  namespace: telegraf
  releaseName: telegraf
  repo: https://helm.influxdata.com/
  valuesFile: helm/values.yaml
  version: 1.1.35
